export const APIFY_LEADS_FINDER_LOCATIONS: string[] = [
  "united states",
  "germany",
  "india",
  "united kingdom",
  "russia",
  "france",
  "china",
  "canada",
  "netherlands",
  "mexico",
  "belgium",
  "japan",
  "brazil",
  "australia",
  "poland",
  "thailand",
  "sweden",
  "portugal",
  "spain",
  "czech republic",
  "taiwan",
  "south africa",
  "colombia",
  "italy",
  "vietnam",
  "nigeria",
  "singapore",
  "hong kong",
  "ireland",
  "israel",
  "switzerland",
  "turkey",
  "romania",
  "south korea",
  "indonesia",
  "united arab emirates",
  "saudi arabia",
  "austria",
  "philippines",
  "peru",
  "malaysia",
  "argentina",
  "ukraine",
  "ghana",
  "denmark",
  "norway",
  "finland",
  "puerto rico",
  "qatar",
  "macau",
  "new zealand",
  "hungary",
  "luxembourg",
  "kuwait",
  "egypt",
  "slovakia",
  "greece",
  "kenya",
  "bulgaria",
  "costa rica",
  "chile",
  "venezuela",
  "afghanistan",
  "bangladesh",
  "malta",
  "guatemala",
  "pakistan",
  "lithuania",
  "panama",
  "morocco",
  "republic of indonesia",
  "uruguay",
  "serbia",
  "bolivia",
  "angola",
  "dominican republic",
  "ecuador",
  "oman",
  "jamaica",
  "zambia",
  "lebanon",
  "tanzania",
  "jordan",
  "algeria",
  "gibraltar",
  "paraguay",
  "cambodia",
  "uganda",
  "mozambique",
  "ethiopia",
  "belarus",
  "republic of the union of myanmar",
  "croatia",
  "jersey",
  "iraq",
  "isle of man",
  "el salvador",
  "estonia",
  "latvia",
  "c\u00f4te d'ivoire",
  "tunisia",
  "sierra leone",
  "senegal",
  "sri lanka",
  "cyprus",
  "kazakhstan",
  "guernsey",
  "bermuda",
  "mali",
  "honduras",
  "bahrain",
  "slovenia",
  "papua new guinea",
  "iceland",
  "mauritius",
  "iran",
  "niger",
  "rwanda",
  "moldova",
  "democratic republic of the congo",
  "liechtenstein",
  "fiji",
  "kyrgyzstan",
  "azerbaijan",
  "madagascar",
  "trinidad and tobago",
  "lesotho",
  "nicaragua",
  "cameroon",
  "barbados",
  "armenia",
  "haiti",
  "maldives",
  "guam",
  "laos",
  "nepal",
  "brunei",
  "reunion",
  "macedonia (fyrom)",
  "swaziland",
  "liberia",
  "uzbekistan",
  "sudan",
  "anguilla",
  "cuba",
  "cayman islands",
  "seychelles",
  "saint kitts and nevis",
  "suriname",
  "bosnia and herzegovina",
  "malawi",
  "the bahamas",
  "botswana",
  "syria",
  "burundi",
  "guadeloupe",
  "namibia",
  "burkina faso",
  "somalia",
  "greenland",
  "equatorial guinea",
  "chad",
  "monaco",
  "republic of the congo",
  "u.s. virgin islands",
  "mayotte",
  "french polynesia",
  "french guiana",
  "andorra",
  "new caledonia",
  "central african republic",
  "myanmar (burma)",
  "belize",
  "aland islands",
  "solomon islands",
  "kosovo",
  "gabon",
  "benin",
  "bonaire, sint eustatius and saba",
  "martinique",
  "tonga",
  "south sudan",
  "cook islands",
  "georgia",
  "mauritania",
  "turkmenistan",
  "libya",
  "falkland islands (islas malvinas)",
  "bhutan",
  "tajikistan",
  "northern mariana islands",
  "western sahara",
  "guyana",
  "dominica",
  "vanuatu",
  "kiribati",
  "togo",
  "nauru",
  "samoa",
  "mongolia",
  "myanmar",
  "yemen",
  "albania",
  "montenegro",
  "california, us",
  "texas, us",
  "england, united kingdom",
  "new york, us",
  "florida, us",
  "illinois, us",
  "moscow, russia",
  "bavaria, germany",
  "pennsylvania, us",
  "virginia, us",
  "ohio, us",
  "massachusetts, us",
  "baden-w\u00fcrttemberg, germany",
  "north rhine-westphalia, germany",
  "georgia, us",
  "michigan, us",
  "north carolina, us",
  "maryland, us",
  "berlin, germany",
  "new jersey, us",
  "bangkok, thailand",
  "\u00eele-de-france, france",
  "maharashtra, india",
  "washington, us",
  "ontario, canada",
  "beijing, china",
  "colorado, us",
  "minnesota, us",
  "karnataka, india",
  "hamburg, germany",
  "indiana, us",
  "shanghai, china",
  "lisbon, portugal",
  "flanders, belgium",
  "arizona, us",
  "ciudad de m\u00e9xico, mexico",
  "wisconsin, us",
  "tennessee, us",
  "missouri, us",
  "saint petersburg, russia",
  "hesse, germany",
  "tamil nadu, india",
  "oregon, us",
  "lower saxony, germany",
  "south carolina, us",
  "connecticut, us",
  "delhi, india",
  "north holland, netherlands",
  "kentucky, us",
  "new south wales, australia",
  "district of columbia, us",
  "telangana, india",
  "iowa, us",
  "guangdong, china",
  "nevada, us",
  "alabama, us",
  "louisiana, us",
  "state of s\u00e3o paulo, brazil",
  "british columbia, canada",
  "utah, us",
  "kansas, us",
  "saxony, germany",
  "lagos, nigeria",
  "nebraska, us",
  "oklahoma, us",
  "overijssel, netherlands",
  "alberta, canada",
  "bogota, colombia",
  "brussels, belgium",
  "south holland, netherlands",
  "dublin, ireland",
  "haryana, india",
  "north brabant, netherlands",
  "uttar pradesh, india",
  "victoria, australia",
  "stockholm county, sweden",
  "moscow oblast, russia",
  "pays de la loire, france",
  "scotland, united kingdom",
  "new hampshire, us",
  "rhineland-palatinate, germany",
  "arkansas, us",
  "utrecht, netherlands",
  "new mexico, us",
  "gujarat, india",
  "dubai, united arab emirates",
  "quebec, canada",
  "bremen, germany",
  "lima, peru",
  "chongqing, china",
  "masovian voivodeship, poland",
  "gelderland, netherlands",
  "chandigarh, india",
  "hanoi, vietnam",
  "provence-alpes-c\u00f4te d'azur, france",
  "mississippi, us",
  "v\u00e4stra g\u00f6taland county, sweden",
  "schleswig-holstein, germany",
  "west virginia, us",
  "jiangsu, china",
  "rhone-alpes, france",
  "zhejiang, china",
  "maine, us",
  "queensland, australia",
  "idaho, us",
  "brandenburg, germany",
  "jalisco, mexico",
  "nord-pas-de-calais, france",
  "auvergne-rh\u00f4ne-alpes, france",
  "aquitaine-limousin-poitou-charentes, france",
  "rhode island, us",
  "saxony-anhalt, germany",
  "north dakota, us",
  "porto district, portugal",
  "delaware, us",
  "catalonia, spain",
  "montana, us",
  "hawaii, us",
  "gauteng, south africa",
  "lower silesian voivodeship, poland",
  "lesser poland voivodeship, poland",
  "western cape, south africa",
  "doha, qatar",
  "madhya pradesh, india",
  "jakarta, indonesia",
  "krasnodar krai, russia",
  "thuringia, germany",
  "kerala, india",
  "bucharest, romania",
  "aquitaine, france",
  "brittany, france",
  "estado de m\u00e9xico, mexico",
  "vienna, austria",
  "riyadh province, saudi arabia",
  "tianjin, china",
  "prague, czech republic",
  "ho chi minh, vietnam",
  "metro manila, philippines",
  "limburg, netherlands",
  "san juan, puerto rico",
  "alaska, us",
  "samara oblast, russia",
  "lombardy, italy",
  "silesian voivodeship, poland",
  "hlavn\u00ed m\u011bsto praha, czech republic",
  "kanagawa prefecture, japan",
  "samut prakan, thailand",
  "rajasthan, india",
  "wales, united kingdom",
  "wyoming, us",
  "puebla, mexico",
  "osaka prefecture, japan",
  "zurich, switzerland",
  "sverdlovsk oblast, russia",
  "western australia, australia",
  "vlaanderen, belgium",
  "south dakota, us",
  "hubei, china",
  "tatarstan, russia",
  "state of rio de janeiro, brazil",
  "tokyo, japan",
  "guanajuato, mexico",
  "sichuan, china",
  "mexico city, mexico",
  "greater accra, ghana",
  "baja california, mexico",
  "mecklenburg-vorpommern, germany",
  "shandong, china",
  "midi-pyr\u00e9n\u00e9es, france",
  "normandy, france",
  "south moravian region, czech republic",
  "nizhny novgorod oblast, russia",
  "budapest, hungary",
  "\u0142\u00f3d\u017a voivodeship, poland",
  "manitoba, canada",
  "auckland, new zealand",
  "alsace, france",
  "walloon region, belgium",
  "federal territory of kuala lumpur, malaysia",
  "novosibirsk oblast, russia",
  "rostov oblast, russia",
  "liaoning, china",
  "nord-pas-de-calais-picardie, france",
  "vermont, us",
  "greater poland voivodeship, poland",
  "fujian, china",
  "alsace-champagne-ardenne-lorraine, france",
  "republic of bashkortostan, russia",
  "state of rio grande do sul, brazil",
  "centre-val de loire, france",
  "chelyabinsk oblast, russia",
  "rh\u00f4ne-alpes, france",
  "saitama prefecture, japan",
  "punjab, india",
  "abu dhabi, united arab emirates",
  "zuid-holland, netherlands",
  "catalunya, spain",
  "santa catarina, brazil",
  "nuevo leon, mexico",
  "aichi prefecture, japan",
  "jilin, china",
  "pomeranian voivodeship, poland",
  "federal capital territory, nigeria",
  "voronezh oblast, russia",
  "veracruz, mexico",
  "skane county, sweden",
  "state of paran\u00e1, brazil",
  "portalegre, portugal",
  "andalusia, spain",
  "federal district, mexico",
  "saskatchewan, canada",
  "quer\u00e9taro, mexico",
  "emilia-romagna, italy",
  "west bengal, india",
  "groningen, netherlands",
  "capital region of denmark, denmark",
  "chiba prefecture, japan",
  "bourgogne-franche-comt\u00e9, france",
  "west java, indonesia",
  "cork, ireland",
  "sk\u00e5ne county, sweden",
  "\u00f6sterg\u00f6tland county, sweden",
  "perm krai, russia",
  "paran\u00e1, brazil",
  "minas gerais, brazil",
  "antioquia, colombia",
  "community of madrid, spain",
  "autonomous city of buenos aires, argentina",
  "languedoc-roussillon-midi-pyr\u00e9n\u00e9es, france",
  "nova scotia, canada",
  "braga, portugal",
  "irkutsk oblast, russia",
  "languedoc-roussillon, france",
  "andhra pradesh, india",
  "oslo, norway",
  "volgograd oblast, russia",
  "lublin voivodeship, poland",
  "moskovskaya oblast', russia",
  "saarland, germany",
  "hokkaido prefecture, japan",
  "lorraine, france",
  "krasnoyarsk krai, russia",
  "state of minas gerais, brazil",
  "selangor, malaysia",
  "setubal, portugal",
  "moravian-silesian region, czech republic",
  "state of mexico, mexico",
  "tula oblast, russia",
  "flevoland, netherlands",
  "hebei, china",
  "centre, france",
  "san luis potosi, mexico",
  "south australia, australia",
  "kyiv city, ukraine",
  "valencian community, spain",
  "central bohemian region, czech republic",
  "luxembourg, luxembourg",
  "galicia, spain",
  "burgundy, france",
  "chihuahua, mexico",
  "hyogo prefecture, japan",
  "lubusz voivodeship, poland",
  "vladimir oblast, russia",
  "saratov oblast, russia",
  "poitou-charentes, france",
  "nairobi, kenya",
  "al asimah, kuwait",
  "uppsala county, sweden",
  "geneva, switzerland",
  "uusimaa, finland",
  "rio grande do sul, brazil",
  "pardubice region, czech republic",
  "kuyavian-pomeranian voivodeship, poland",
  "shaanxi, china",
  "qu\u00e9bec, canada",
  "yaroslavl oblast, russia",
  "olomouc region, czech republic",
  "basque country, spain",
  "fukuoka prefecture, japan",
  "new brunswick, canada",
  "udmurt republic, russia",
  "kemerovo oblast, russia",
  "khanty-mansi autonomous okrug, russia",
  "anhui, china",
  "tver oblast, russia",
  "shanghai shi, china",
  "leningrad oblast, russia",
  "northern ireland, united kingdom",
  "australian capital territory, australia",
  "jonkoping county, sweden",
  "krasnodarskiy kray, russia",
  "aguascalientes, mexico",
  "bihar, india",
  "lazio, italy",
  "west pomeranian voivodeship, poland",
  "veneto, italy",
  "ulyanovsk oblast, russia",
  "lombardia, italy",
  "plze\u0148 region, czech republic",
  "udmurtskaja respublika, russia",
  "altai krai, russia",
  "omsk oblast, russia",
  "ibaraki prefecture, japan",
  "vaud, switzerland",
  "ilfov county, romania",
  "ryazan oblast, russia",
  "orenburg oblast, russia",
  "odisha, india",
  "lower austria, austria",
  "champagne-ardenne, france",
  "upper austria, austria",
  "kaluga oblast, russia",
  "kwazulu-natal, south africa",
  "friesland, netherlands",
  "s\u00f6dermanland county, sweden",
  "warmian-masurian voivodeship, poland",
  "jiangxi, china",
  "uttarakhand, india",
  "piemonte, italy",
  "tyumen oblast, russia",
  "eastern cape, south africa",
  "belgorod oblast, russia",
  "shizuoka prefecture, japan",
  "\u00fast\u00ed nad labem region, czech republic",
  "castile and le\u00f3n, spain",
  "makkah province, saudi arabia",
  "newfoundland and labrador, canada",
  "khabarovsk krai, russia",
  "franche-comt\u00e9, france",
  "hunan, china",
  "primorsky krai, russia",
  "penza oblast, russia",
  "wallonie, belgium",
  "chuvashia republic, russia",
  "noord-holland, netherlands",
  "state of bahia, brazil",
  "nagano prefecture, japan",
  "south bohemian region, czech republic",
  "jharkhand, india",
  "kirov oblast, russia",
  "vologda oblast, russia",
  "yucat\u00e1n, mexico",
  "hradec kr\u00e1lov\u00e9 region, czech republic",
  "drenthe, netherlands",
  "dalarna county, sweden",
  "sonora, mexico",
  "miyagi prefecture, japan",
  "arkhangelsk oblast, russia",
  "v\u00e4stmanland county, sweden",
  "\u00f6rebro county, sweden",
  "auvergne, france",
  "styria, austria",
  "lisboa, portugal",
  "v\u00e4sterbotten county, sweden",
  "hiroshima prefecture, japan",
  "henan, china",
  "heilongjiang, china",
  "kronoberg county, sweden",
  "mie prefecture, japan",
  "comunidad de madrid, spain",
  "liberec region, czech republic",
  "stavropol krai, russia",
  "\u0e08\u0e31\u0e07\u0e2b\u0e27\u0e31\u0e14 \u0e01\u0e23\u0e38\u0e07\u0e40\u0e17\u0e1e\u0e21\u0e2b\u0e32\u0e19\u0e04\u0e23, thailand",
  "tomsk oblast, russia",
  "ivanovo oblast, russia",
  "bryansk oblast, russia",
  "halland county, sweden",
  "andaluc\u00eda, spain",
  "lipetsk oblast, russia",
  "federal district, brazil",
  "galway, ireland",
  "upper normandy, france",
  "smolensk oblast, russia",
  "vlaams gewest, belgium",
  "vysocina region, czech republic",
  "kyoto prefecture, japan",
  "cluj county, romania",
  "norrbotten county, sweden",
  "murmansk oblast, russia",
  "bayern, germany",
  "varmland county, sweden",
  "distrito federal, mexico",
  "eastern province, saudi arabia",
  "wellington, new zealand",
  "hidalgo, mexico",
  "calabarzon, philippines",
  "tochigi prefecture, japan",
  "salzburg, austria",
  "nuevo le\u00f3n, mexico",
  "da nang, vietnam",
  "himachal pradesh, india",
  "zlin region, czech republic",
  "v\u00e4sternorrland county, sweden",
  "central denmark region, denmark",
  "nonthaburi, thailand",
  "oyo, nigeria",
  "bratislava region, slovakia",
  "cairo governorate, egypt",
  "podkarpackie voivodeship, poland",
  "oaxaca, mexico",
  "arequipa, peru",
  "state of cear\u00e1, brazil",
  "kalmar county, sweden",
  "san jose, costa rica",
  "guizhou, china",
  "kursk oblast, russia",
  "basel-stadt, switzerland",
  "prince edward island, canada",
  "attica, greece",
  "normandie, france",
  "gavleborg county, sweden",
  "noord-brabant, netherlands",
  "chhattisgarh, india",
  "faro district, portugal",
  "cundinamarca, colombia",
  "oryol oblast, russia",
  "karlovy vary region, czech republic",
  "chiapas, mexico",
  "penang, malaysia",
  "kostroma oblast, russia",
  "shanxi, china",
  "fukushima prefecture, japan",
  "valle del cauca, colombia",
  "tambov oblast, russia",
  "state of santa catarina, brazil",
  "hainan, china",
  "yamalo-nenets autonomous okrug, russia",
  "puducherry, india",
  "limousin, france",
  "sinaloa, mexico",
  "coimbra district, portugal",
  "kaliningrad oblast, russia",
  "alagoas, brazil",
  "astrakhan oblast, russia",
  "yamaguchi prefecture, japan",
  "trentino-alto adige/south tyrol, italy",
  "novgorod oblast, russia",
  "b\u00ecnh d\u01b0\u01a1ng, vietnam",
  "sofia city province, bulgaria",
  "atlantico, colombia",
  "gifu prefecture, japan",
  "niigata prefecture, japan",
  "castile-la mancha, spain",
  "opole voivodeship, poland",
  "gansu, china",
  "kabul, afghanistan",
  "rivers, nigeria",
  "pskov oblast, russia",
  "gunma prefecture, japan",
  "lower normandy, france",
  "johor, malaysia",
  "state of pernambuco, brazil",
  "ankara province, turkey",
  "limerick, ireland",
  "mari el republic, russia",
  "canton of bern, switzerland",
  "lapland, finland",
  "guatemala, guatemala",
  "phuket, thailand",
  "kumamoto prefecture, japan",
  "akershus, norway",
  "okayama prefecture, japan",
  "tyrol, austria",
  "rheinland-pfalz, germany",
  "blekinge county, sweden",
  "durango, mexico",
  "jamtland county, sweden",
  "guaynabo, puerto rico",
  "chachoengsao, thailand",
  "santiago metropolitan region, chile",
  "piedmont, italy",
  "yunnan, china",
  "toscana, italy",
  "tasmania, australia",
  "region syddanmark, denmark",
  "coahuila de zaragoza, mexico",
  "republic of karelia, russia",
  "castilla y le\u00f3n, spain",
  "colima, mexico",
  "free state, south africa",
  "bursa, turkey",
  "niedersachsen, germany",
  "nunavut, canada",
  "gyeonggi-do, south korea",
  "arag\u00f3n, spain",
  "komi republic, russia",
  "santander department, colombia",
  "canton of solothurn, switzerland",
  "euskadi, spain",
  "kurgan oblast, russia",
  "aragon, spain",
  "northern territory, australia",
  "nagasaki prefecture, japan",
  "esp\u00edrito santo, brazil",
  "mordovia, russia",
  "th\u00fcringen, germany",
  "respublika bashkortostan, russia",
  "kaluzhskaya oblast', russia",
  "bern, switzerland",
  "rajshahi division, bangladesh",
  "sachsen-anhalt, germany",
  "hordaland, norway",
  "buryatia, russia",
  "nordrhein-westfalen, germany",
  "mato grosso, brazil",
  "nara prefecture, japan",
  "guangxi, china",
  "zabaykalsky krai, russia",
  "san luis potos\u00ed, mexico",
  "tamaulipas, mexico",
  "east java, indonesia",
  "timi\u0219 county, romania",
  "east kalimantan, indonesia",
  "cantabria, spain",
  "tuscany, italy",
  "yucatan, mexico",
  "amur oblast, russia",
  "khon kaen, thailand",
  "sibiu, romania",
  "state of goi\u00e1s, brazil",
  "canary islands, spain",
  "sachsen, germany",
  "goi\u00e1s, brazil",
  "rostovskaya oblast', russia",
  "piura, peru",
  "dnipropetrovsk oblast, ukraine",
  "bra\u0219ov county, romania",
  "vila real, portugal",
  "amazonas, brazil",
  "st. gallen, switzerland",
  "sakha republic, russia",
  "maranh\u00e3o, brazil",
  "navarre, spain",
  "taiwan province, taiwan",
  "leningradskaya oblast', russia",
  "regi\u00f3n de murcia, spain",
  "picardy, france",
  "kano, nigeria",
  "ishikawa prefecture, japan",
  "ehime prefecture, japan",
  "podlaskie voivodeship, poland",
  "gen\u00e8ve, switzerland",
  "comunidad valenciana, spain",
  "north sumatra, indonesia",
  "tel aviv district, israel",
  "carinthia, austria",
  "yamagata prefecture, japan",
  "odessa oblast, ukraine",
  "campeche, mexico",
  "center district, israel",
  "sakhalin oblast, russia",
  "waterford, ireland",
  "mato grosso do sul, brazil",
  "michoac\u00e1n, mexico",
  "campania, italy",
  "viseu district, portugal",
  "extremadura, spain",
  "iwate prefecture, japan",
  "canarias, spain",
  "kandahar, afghanistan",
  "alexandria governorate, egypt",
  "panama, panama",
  "kharkiv oblast, ukraine",
  "shiga prefecture, japan",
  "balearic islands, spain",
  "kaduna, nigeria",
  "miyazaki prefecture, japan",
  "canton of fribourg, switzerland",
  "risaralda, colombia",
  "republic of khakassia, russia",
  "tlaxcala, mexico",
  "principado de asturias, spain",
  "riau islands, indonesia",
  "lviv oblast, ukraine",
  "lucerne, switzerland",
  "borsod-aba\u00faj-zempl\u00e9n, hungary",
  "ciudad aut\u00f3noma de buenos aires, argentina",
  "ia\u0219i county, romania",
  "pernambuco, brazil",
  "kagawa prefecture, japan",
  "tyumenskaya oblast', russia",
  "canton of zug, switzerland",
  "par\u00e1, brazil",
  "punjab, pakistan",
  "castilla-la mancha, spain",
  "corsica, france",
  "sharjah, united arab emirates",
  "castelo branco district, portugal",
  "rogaland, norway",
  "quintana roo, mexico",
  "santar\u00e9m district, portugal",
  "toyama prefecture, japan",
  "kagoshima prefecture, japan",
  "ticino, switzerland",
  "aargau, switzerland",
  "departamento de lima, peru",
  "kardzhali province, bulgaria",
  "constan\u021ba county, romania",
  "saga prefecture, japan",
  "para\u00edba, brazil",
  "troms, norway",
  "lusaka, zambia",
  "cordoba, argentina",
  "parvan, afghanistan",
  "enugu, nigeria",
  "region zealand, denmark",
  "asturias, spain",
  "sverdlovskaya oblast', russia",
  "wakayama prefecture, japan",
  "rio grande do norte, brazil",
  "bol\u00edvar, venezuela",
  "friuli-venezia giulia, italy",
  "krung thep maha nakhon, thailand",
  "vorarlberg, austria",
  "umbria, italy",
  "ningxia, china",
  "burgenland, austria",
  "montevideo department, uruguay",
  "oita prefecture, japan",
  "banten, republic of indonesia",
  "chon buri, thailand",
  "kildare, ireland",
  "coahuila, mexico",
  "fukui prefecture, japan",
  "magadan oblast, russia",
  "south sulawesi, indonesia",
  "aomori prefecture, japan",
  "inner mongolia, china",
  "marche, italy",
  "ogun state, nigeria",
  "central visayas, philippines",
  "k\u00fctahya, turkey",
  "tolima, colombia",
  "jigawa, nigeria",
  "vilnius county, lithuania",
  "s\u00f8r-tr\u00f8ndelag, norway",
  "prahova, romania",
  "santa fe province, argentina",
  "cear\u00e1, brazil",
  "beja, portugal",
  "north district, israel",
  "aveiro district, portugal",
  "grand casablanca, morocco",
  "altayskiy kray, russia",
  "meta, colombia",
  "la libertad, peru",
  "canton of neuch\u00e2tel, switzerland",
  "nayarit, mexico",
  "state of esp\u00edrito santo, brazil",
  "liguria, italy",
  "nakhon nayok, thailand",
  "addis ababa, ethiopia",
  "kyivs'ka oblast, ukraine",
  "viana do castelo, portugal",
  "chechenskaya republits, russia",
  "bahia, brazil",
  "carolina, puerto rico",
  "ti\u1ec1n giang, vietnam",
  "acre, brazil",
  "sicilia, italy",
  "kabardino-balkaria, russia",
  "hedmark, norway",
  "cusco, peru",
  "songkhla, thailand",
  "canterbury, new zealand",
  "okinawa prefecture, japan",
  "brussel, belgium",
  "phnom penh, cambodia",
  "\u00e9vora district, portugal",
  "zaporiz'ka oblast, ukraine",
  "katsina, nigeria",
  "north denmark region, denmark",
  "central java, indonesia",
  "nizhegorodskaya oblast', russia",
  "stockholms l\u00e4n, sweden",
  "sa kaeo, thailand",
  "ponce, puerto rico",
  "prachuap khiri khan, thailand",
  "gotland county, sweden",
  "piau\u00ed, brazil",
  "nordland, norway",
  "kamchatka krai, russia",
  "qinghai, china",
  "irkutskaya oblast', russia",
  "dagestan republic, russia",
  "rangpur division, bangladesh",
  "jude\u021bul bihor, romania",
  "la rioja, spain",
  "caguas, puerto rico",
  "yamanashi prefecture, japan",
  "buenos aires province, argentina",
  "central luzon, philippines",
  "mykolaivs'ka oblast, ukraine",
  "h\u1ed3 ch\u00ed minh, vietnam",
  "narino, colombia",
  "gala\u021bi, romania",
  "zakarpats'ka oblast, ukraine",
  "kemerovskaya oblast', russia",
  "akita prefecture, japan",
  "khanty-mansiyskiy avtonomnyy okrug, russia",
  "cajamarca, peru",
  "cauca department, colombia",
  "bihor county, romania",
  "kilkenny, ireland",
  "malacca, malaysia",
  "gaziantep, turkey",
  "davao region, philippines",
  "stavropolskiy kray, russia",
  "jude\u021bul timi\u0219, romania",
  "tokushima prefecture, japan",
  "tottori prefecture, japan",
  "limpopo, south africa",
  "samarskaya oblast', russia",
  "adana, turkey",
  "hessen, germany",
  "swietokrzyskie, poland",
  "bing\u00f6l, turkey",
  "caldas, colombia",
  "\u00f8stfold, norway",
  "aichi-ken, japan",
  "b\u00e0 r\u1ecba - v\u0169ng t\u00e0u, vietnam",
  "orenburgskaya oblast', russia",
  "san salvador, el salvador",
  "boyaca, colombia",
  "tverskaya oblast', russia",
  "shimane prefecture, japan",
  "canton of schaffhausen, switzerland",
  "bayam\u00f3n, puerto rico",
  "ondo, nigeria",
  "haiphong, vietnam",
  "illes balears, spain",
  "hunedoara county, romania",
  "western, ghana",
  "trentino-alto adige, italy",
  "kanchanaburi, thailand",
  "northwest territories, canada",
  "donegal, ireland",
  "guerrero, mexico",
  "jude\u021bul cluj, romania",
  "ba ria - vung tau, vietnam",
  "saratovskaya oblast', russia",
  "dorado, puerto rico",
  "northern, ghana",
  "konya, turkey",
  "huila, colombia",
  "khersons'ka oblast, ukraine",
  "volgogradskaya oblast', russia",
  "junin, peru",
  "north ossetia\u2013alania, russia",
  "santo domingo, dominican republic",
  "special region of yogyakarta, indonesia",
  "bali, indonesia",
  "entre rios, argentina",
  "adygea, russia",
  "puglia, italy",
  "special capital region of jakarta, indonesia",
  "guarda district, portugal",
  "chuvashia, russia",
  "yukon territory, canada",
  "tulskaya oblast', russia",
  "pichincha, ecuador",
  "appenzell outer rhodes, switzerland",
  "carabobo, venezuela",
  "m\u00f8re og romsdal, norway",
  "buskerud, norway",
  "kocaeli, turkey",
  "bengkulu, indonesia",
  "kalmykia, russia",
  "altai republic, russia",
  "poltavs'ka oblast, ukraine",
  "arge\u0219 county, romania",
  "leiria district, portugal",
  "ialomi\u021ba county, romania",
  "calabria, italy",
  "tunceli, turkey",
  "bac\u0103u county, romania",
  "north west, south africa",
  "dolj county, romania",
  "smolenskaya oblast', russia",
  "jude\u021bul mure\u0219, romania",
  "vestfold, norway",
  "la paz department, bolivia",
  "north santander, colombia",
  "luanda, angola",
  "teleorman county, romania",
  "beijing shi, china",
  "louth, ireland",
  "rivnens'ka oblast, ukraine",
  "jambi, indonesia",
  "sergipe, brazil",
  "set\u00fabal, portugal",
  "al madinah province, saudi arabia",
  "amap\u00e1, brazil",
  "vest-agder, norway",
  "riau, indonesia",
  "udon thani, thailand",
  "cordoba, colombia",
  "jude\u021bul suceava, romania",
  "voronezhskaya oblast', russia",
  "islamabad capital territory, pakistan",
  "fej\u00e9r, hungary",
  "hu\u00edla, angola",
  "donetsk oblast, ukraine",
  "moquegua, peru",
  "long an, vietnam",
  "state of rond\u00f4nia, brazil",
  "sligo, ireland",
  "c\u1ea7n th\u01a1, vietnam",
  "sums'ka oblast, ukraine",
  "assam, india",
  "jude\u021bul prahova, romania",
  "tocantins, brazil",
  "waikato, new zealand",
  "lipetskaya oblast', russia",
  "quindio, colombia",
  "valais, switzerland",
  "oppland, norway",
  "phitsanulok, thailand",
  "basel-landschaft, switzerland",
  "pahang, malaysia",
  "surat thani, thailand",
  "vrancea county, romania",
  "vinnyts'ka oblast, ukraine",
  "south district, israel",
  "navarra, spain",
  "wicklow, ireland",
  "alba county, romania",
  "algiers, algeria",
  "belgorodskaya oblast', russia",
  "melilla, spain",
  "zhytomyrs'ka oblast, ukraine",
  "d\u00e2mbovi\u021ba county, romania",
  "ceuta, spain",
  "west kalimantan, indonesia",
  "wexford, ireland",
  "harghita county, romania",
  "szabolcs-szatm\u00e1r-bereg, hungary",
  "meath, ireland",
  "otago, new zealand",
  "neam\u021b county, romania",
  "arkhangelskaya oblast', russia",
  "bol\u00edvar, colombia",
  "manawatu-wanganui, new zealand",
  "chisinau, moldova",
  "santa cruz, bolivia",
  "magdalena, colombia",
  "niamey, niger",
  "kochi prefecture, japan",
  "krasnoyarskiy kray, russia",
  "caracas metropolitan district, venezuela",
  "daman and diu, india",
  "mendoza province, argentina",
  "bamako, mali",
  "south sumatra, indonesia",
  "tucum\u00e1n, argentina",
  "jude\u021bul maramure\u0219, romania",
  "banten, indonesia",
  "bitlis, turkey",
  "dakar, senegal",
  "tambovskaya oblast', russia",
  "abruzzo, italy",
  "bretagne, france",
  "olt county, romania",
  "nitra region, slovakia",
  "hai duong, vietnam",
  "huanuco, peru",
  "ivano-frankivs'ka oblast, ukraine",
  "chiang rai, thailand",
  "westmeath, ireland",
  "kom\u00e1rom-esztergom, hungary",
  "jude\u021bul ia\u0219i, romania",
  "cherkas'ka oblast, ukraine",
  "r\u00e9gion wallonne, belgium",
  "west sumatra, indonesia",
  "omskaya oblast', russia",
  "dong nai, vietnam",
  "northern ostrobothnia, finland",
  "kedah, malaysia",
  "muscat governorate, oman",
  "jewish autonomous oblast, russia",
  "karachay-cherkessia, russia",
  "bal\u0131kesir, turkey",
  "satu mare county, romania",
  "haifa district, israel",
  "ashanti, ghana",
  "apulia, italy",
  "corrientes province, argentina",
  "cara\u0219-severin county, romania",
  "zulia, venezuela",
  "arad county, romania",
  "central region, uganda",
  "gwangju, south korea",
  "kirovskaya oblast', russia",
  "grisons, switzerland",
  "respublika adygeya, russia",
  "khyber pakhtunkhwa, pakistan",
  "buz\u0103u county, romania",
  "suceava county, romania",
  "thurgau, switzerland",
  "roscommon, ireland",
  "kujawsko-pomorskie, poland",
  "arusha, tanzania",
  "madre de dios, peru",
  "la pampa province, argentina",
  "chechnya, russia",
  "heves county, hungary",
  "tehran, iran",
  "beirut, lebanon",
  "tacna, peru",
  "sakarya, turkey",
  "permskiy kray, russia",
  "northern cape, south africa",
  "sofia-city, bulgaria",
  "bansk\u00e1 bystrica region, slovakia",
  "amman, jordan",
  "special capital region of jakarta, republic of indonesia",
  "neuquen, argentina",
  "negeri sembilan, malaysia",
  "rabat-sale-zemmour-zaer, morocco",
  "wojew\u00f3dztwo dolno\u015bl\u0105skie, poland",
  "maputo city, mozambique",
  "telemark, norway",
  "samsun, turkey",
  "edo, nigeria",
  "tabasco, mexico",
  "city of zagreb, croatia",
  "lambayeque, peru",
  "bay of plenty, new zealand",
  "aust-agder, norway",
  "lagunes, c\u00f4te d'ivoire",
  "cartago, costa rica",
  "pest county, hungary",
  "gombe, nigeria",
  "sindh, pakistan",
  "br\u0103ila county, romania",
  "kaliningradskaya oblast', russia",
  "papua, indonesia",
  "kayseri province, turkey",
  "c\u0103l\u0103ra\u0219i county, romania",
  "orlovskaya oblast', russia",
  "bing\u00f6l province, turkey",
  "sokoto, nigeria",
  "diyarbak\u0131r, turkey",
  "volyns'ka oblast, ukraine",
  "ingushetia, russia",
  "nenetskiy, russia",
  "trnava region, slovakia",
  "ivanovskaya oblast', russia",
  "hajd\u00fa-bihar, hungary",
  "tuva, russia",
  "pa\u00eds vasco, spain",
  "western area, sierra leone",
  "ulyanovskaya oblast', russia",
  "lampung, indonesia",
  "minsk region, belarus",
  "vologodskaya oblast', russia",
  "aguadilla, puerto rico",
  "nieder\u00f6sterreich, austria",
  "xizang (tibet), china",
  "ternopil's'ka oblast, ukraine",
  "bryanskaya oblast', russia",
  "maseru, lesotho",
  "giza governorate, egypt",
  "hong kong island, hong kong",
  "mure\u0219 county, romania",
  "gorontalo, indonesia",
  "tomskaya oblast', russia",
  "carlow, ireland",
  "eski\u015fehir province, turkey",
  "gyeongsangbuk-do, south korea",
  "t\u014dky\u014d-to, japan",
  "chelyabinskaya oblast', russia",
  "vaslui county, romania",
  "ryazanskaya oblast', russia",
  "suphan buri, thailand",
  "kostromskaya oblast', russia",
  "lima region, peru",
  "sardegna, italy",
  "central kalimantan, indonesia",
  "covasna county, romania",
  "casanare, colombia",
  "kurskaya oblast', russia",
  "yaroslavskaya oblast', russia",
  "kigali, rwanda",
  "dhaka division, bangladesh",
  "vladimirskaya oblast', russia",
  "zacatecas, mexico",
  "xinjiang, china",
  "aceh, indonesia",
  "steiermark, austria",
  "cordillera administrative region, philippines",
  "gyeongsangnam-do, south korea",
  "chukotka autonomous okrug, russia",
  "burgandy, france",
  "luzern, switzerland",
  "cesar, colombia",
  "l\u00e2m \u0111\u1ed3ng, vietnam",
  "hamilton, bermuda",
  "bauchi, nigeria",
  "san jos\u00e9, costa rica",
  "baghd\u0101d, iraq",
  "east java, republic of indonesia",
  "chernihivs'ka oblast, ukraine",
  "basilicata, italy",
  "novosibirskaya oblast', russia",
  "varna, bulgaria",
  "chubut province, argentina",
  "chungcheongbuk-do, south korea",
  "gy\u00f5r-moson-sopron, hungary",
  "national district, dominican republic",
  "tirol, austria",
  "nord-pas-de-calais picardie, france",
  "thai nguyen, vietnam",
  "jude\u021bul arad, romania",
  "basrah, iraq",
  "northern mindanao, philippines",
  "tulcea county, romania",
  "roraima, brazil",
  "edirne, turkey",
  "borno, nigeria",
  "putrajaya, malaysia",
  "mizoram, india",
  "boyac\u00e1, colombia",
  "salta province, argentina",
  "kerry, ireland",
  "sucre, colombia",
  "mehedin\u021bi county, romania",
  "constantine, algeria",
  "jude\u021bul v\u00e2lcea, romania",
  "mazowieckie, poland",
  "vojvodina, serbia",
  "b\u00ecnh ph\u01b0\u1edbc, vietnam",
  "cabo rojo, puerto rico",
  "canton of schwyz, switzerland",
  "setif, algeria",
  "perak, malaysia",
  "respublika tatarstan, russia",
  "respublika kalmykiya, russia",
  "ayacucho, peru",
  "clare, ireland",
  "san luis province, argentina",
  "osun, nigeria",
  "astrakhanskaya oblast', russia",
  "jude\u021bul sibiu, romania",
  "ober\u00f6sterreich, austria",
  "madeira, portugal",
  "b\u1ea1c li\u00eau, vietnam",
  "gisborne, new zealand",
  "luhans'ka oblast, ukraine",
  "south east sulawesi, indonesia",
  "chernivets'ka oblast, ukraine",
  "boto\u0219ani county, romania",
  "toamasina, madagascar",
  "maluku, indonesia",
  "southland, new zealand",
  "western visayas, philippines",
  "mayag\u00fcez, puerto rico",
  "kaunas county, lithuania",
  "plovdiv province, bulgaria",
  "rond\u00f4nia, brazil",
  "sabah, malaysia",
  "port of spain, trinidad and tobago",
  "laikipia, kenya",
  "klaip\u0117da county, lithuania",
  "mardin, turkey",
  "penzenskaya oblast', russia",
  "kamchatskiy kray, russia",
  "giurgiu county, romania",
  "toa baja, puerto rico",
  "nampula, mozambique",
  "kalasin, thailand",
  "jeollabuk-do, south korea",
  "ahmadi, kuwait",
  "west nusa tenggara, indonesia",
  "distrito federal, brazil",
  "tren\u010d\u00edn region, slovakia",
  "harju county, estonia",
  "guayas, ecuador",
  "sarawak, malaysia",
  "mayo, ireland",
  "\u0627\u0644\u0631\u064a\u0627\u0646, qatar",
  "huancavelica, peru",
  "kinshasa, democratic republic of the congo",
  "north sulawesi, indonesia",
  "kirovohrads'ka oblast, ukraine",
  "veszpr\u00e9m, hungary",
  "haute-normandie, france",
  "maramure\u0219 county, romania",
  "t\u00e2y ninh province, vietnam",
  "nagaland, india",
  "sogn og fjordane, norway",
  "\u017eilina region, slovakia",
  "ajman, united arab emirates",
  "\u015fanl\u0131urfa, turkey",
  "v\u00e4stra g\u00f6talands l\u00e4n, sweden",
  "miranda, venezuela",
  "humacao, puerto rico",
  "nghe an, vietnam",
  "riga, latvia",
  "molise, italy",
  "ancash, peru",
  "bragan\u00e7a, portugal",
  "chungcheongnam-do, south korea",
  "malatya, turkey",
  "ko\u0161ice region, slovakia",
  "murmanskaya oblast', russia",
  "bayburt, turkey",
  "heredia province, costa rica",
  "s\u0103laj, romania",
  "graub\u00fcnden, switzerland",
  "finnmark, norway",
  "gangwon-do, south korea",
  "volta, ghana",
  "bragan\u00e7a district, portugal",
  "sankt gallen, switzerland",
  "managua, nicaragua",
  "respublika mordoviya, russia",
  "ninh b\u00ecnh province, vietnam",
  "kowloon, hong kong",
  "dzhalal-abadskaya, kyrgyzstan",
  "yangon region, republic of the union of myanmar",
  "sakon nakhon, thailand",
  "jude\u021bul alba, romania",
  "jujuy, argentina",
  "kareliya republits, russia",
  "quebradillas, puerto rico",
  "nakhon sawan, thailand",
  "north maluku, indonesia",
  "jazan, saudi arabia",
  "monaghan, ireland",
  "languedoc-roussillon midi-pyr\u00e9n\u00e9es, france",
  "saint james, barbados",
  "gia lai province, vietnam",
  "phra nakhon si ayutthaya, thailand",
  "nord-trondelag, norway",
  "novgorodskaya oblast', russia",
  "sofia province, bulgaria",
  "bolivar, colombia",
  "santander, colombia",
  "imo, nigeria",
  "saint james parish, jamaica",
  "ma\u0142opolskie, poland",
  "primorskiy kray, russia",
  "san juan province, argentina",
  "northeast, iceland",
  "trujillo alto, puerto rico",
  "capital district, venezuela",
  "bueng kan, thailand",
  "burgas, bulgaria",
  "nakuru, kenya",
  "canton of jura, switzerland",
  "khmel'nyts'ka oblast, ukraine",
  "hatillo, puerto rico",
  "antofagasta region, chile",
  "canton of obwalden, switzerland",
  "western province, sri lanka",
  "upper east, ghana",
  "luquillo, puerto rico",
  "podlaskie, poland",
  "capital governorate, bahrain",
  "can\u00f3vanas, puerto rico",
  "konya province, turkey",
  "central governorate, bahrain",
  "lo\u00edza, puerto rico",
  "r\u00edo negro, argentina",
  "taranaki, new zealand",
  "caquet\u00e1, colombia",
  "triesen, liechtenstein",
  "central, ghana",
  "silistra, bulgaria",
  "siirt, turkey",
  "azores, portugal",
  "dagestan republits, russia",
  "northland, new zealand",
  "ouargla, algeria",
  "central sulawesi, indonesia",
  "almaty region, kazakhstan",
  "binh thuan, vietnam",
  "guangdong sheng, china",
  "jude\u021bul dolj, romania",
  "hatay, turkey",
  "khabarovskiy kray, russia",
  "jeju-do, south korea",
  "anzoategui, venezuela",
  "\u015fanl\u0131urfa province, turkey",
  "sor-trondelag, norway",
  "sandys, bermuda",
  "kien giang, vietnam",
  "tolna county, hungary",
  "west java, republic of indonesia",
  "chai nat, thailand",
  "tianjin shi, china",
  "jude\u021bul constan\u021ba, romania",
  "leitrim, ireland",
  "marlborough, new zealand",
  "al khor, qatar",
  "arauca, colombia",
  "erzincan, turkey",
  "kurganskaya oblast', russia",
  "eastern region, uganda",
  "chaco province, argentina",
  "ljubljana, slovenia",
  "canton of glarus, switzerland",
  "cochabamba department, bolivia",
  "\u00e7ank\u0131r\u0131, turkey",
  "alger, algeria",
  "vas county, hungary",
  "bourgogne franche-comt\u00e9, france",
  "apurimac, peru",
  "nam dinh, vietnam",
  "sicily, italy",
  "aseer province, saudi arabia",
  "kiambu, kenya",
  "kogi, nigeria",
  "viana do castelo district, portugal",
  "crete, greece",
  "pirkanmaa, finland",
  "nangarhar, afghanistan",
  "v\u00e4rmlands l\u00e4n, sweden",
  "santar\u00e9m, portugal",
  "region of murcia, spain",
  "makedonia thraki, greece",
  "j\u00e1sz-nagykun-szolnok, hungary",
  "fes-boulemane, morocco",
  "csongr\u00e1d, hungary",
  "tipperary, ireland",
  "zabaykalskiy kray, russia",
  "van, turkey",
  "k\u0131rklareli, turkey",
  "santiago, dominican republic",
  "catalu\u00f1a, spain",
  "east nusa tenggara, indonesia",
  "northern borders province, saudi arabia",
  "siem reap, cambodia",
  "fajardo, puerto rico",
  "b\u00edo b\u00edo region, chile",
  "hormigueros, puerto rico",
  "delta, nigeria",
  "west papua, indonesia",
  "jayuya, puerto rico",
  "t\u00e1chira, venezuela",
  "san martin, peru",
  "kymenlaakso, finland",
  "wielkopolskie, poland",
  "offaly, ireland",
  "upper west, ghana",
  "fujairah, united arab emirates",
  "koungou, mayotte",
  "tete, mozambique",
  "valle d'aosta, italy",
  "wien, austria",
  "saint-paul, reunion",
  "herat, afghanistan",
  "b\u00e1cs-kiskun, hungary",
  "ilocos region, philippines",
  "gabrovo, bulgaria",
  "thai binh, vietnam",
  "m\u00e9rida, venezuela",
  "denizli, turkey",
  "cagayan valley, philippines",
  "panev\u0117\u017eys county, lithuania",
  "jerusalem district, israel",
  "saint mary parish, jamaica",
  "stara zagora, bulgaria",
  "buryatiya republits, russia",
  "catamarca province, argentina",
  "port said governorate, egypt",
  "al qalyubia governorate, egypt",
  "tuy\u00ean quang province, vietnam",
  "thua thien hue, vietnam",
  "bourgogne, france",
  "peloponnisos dytiki ellada ke ionio, greece",
  "tangier-tetouan, morocco",
  "respublika mariy el, russia",
  "choco, colombia",
  "binh dinh province, vietnam",
  "valparaiso region, chile",
  "northern region, uganda",
  "putumayo, colombia",
  "saint thomas lowland parish, saint kitts and nevis",
  "granma, cuba",
  "komi republits, russia",
  "land salzburg, austria",
  "yamalo-nenetskiy, russia",
  "cross river, nigeria",
  "santa cruz province, argentina",
  "tierra del fuego province, argentina",
  "formosa province, argentina",
  "san andr\u00e9s y providencia, colombia",
  "tien giang, vietnam",
  "thessalia sterea ellada, greece",
  "baja california sur, mexico",
  "hato mayor, dominican republic",
  "eastern, ghana",
  "ras al khaimah, united arab emirates",
  "k\u00e4rnten, austria",
  "ceiba, puerto rico",
  "ostfold, norway",
  "jude\u021bul hunedoara, romania",
  "orellana, ecuador",
  "yabucoa, puerto rico",
  "anambra, nigeria",
  "\u0161iauliai county, lithuania",
  "la rioja province, argentina",
  "brong ahafo, ghana",
  "al batinah north governorate, oman",
  "a\u00f1asco, puerto rico",
  "cuzco, peru",
  "atl\u00e1ntico, colombia",
  "hhohho, swaziland",
  "marrakesh-tensift-el haouz, morocco",
  "plaines wilhems, mauritius",
  "national capital district, papua new guinea",
  "bioko norte, equatorial guinea",
  "pre\u0161ov region, slovakia",
  "yerevan, armenia",
  "naguabo, puerto rico",
  "central finland, finland",
  "westmoreland parish, jamaica",
  "r\u012bgas pils\u0113ta, latvia",
  "h\u00e0 giang, vietnam",
  "mwanza, tanzania",
  "jude\u021bul gala\u021bi, romania",
  "mombasa, kenya",
  "santiago del estero province, argentina",
  "shinyanga, tanzania",
  "appenzell innerrhoden, switzerland",
  "gurabo, puerto rico",
  "khartoum, sudan",
  "cidra, puerto rico",
  "panam\u00e1, panama",
  "amurskaya oblast', russia",
  "toa alta, puerto rico",
  "hawke's bay, new zealand",
  "bal\u0131kesir province, turkey",
  "vientiane prefecture, laos",
  "guayama, puerto rico",
  "distrito de beja, portugal",
  "juana d\u00edaz, puerto rico",
  "vic, australia",
  "ipiros ditiki makedonia, greece",
  "phetchabun, thailand",
  "adamawa, nigeria",
  "kigoma, tanzania",
  "francisco morazan, honduras",
  "bicol, philippines",
  "beni department, bolivia",
  "bujumbura mairie, burundi",
  "cavan, ireland",
  "\u0e0a\u0e31\u0e22\u0e20\u0e39\u0e21\u0e34, thailand",
  "h\u00f2a b\u00ecnh, vietnam",
  "freiburg, switzerland",
  "cayey, puerto rico",
  "k\u0131r\u015fehir, turkey",
  "fukushima-ken, japan",
  "monagas, venezuela",
  "blagoevgrad province, bulgaria",
  "ucayali, peru",
  "lara, venezuela",
  "canelones, uruguay",
  "west coast, new zealand",
  "zala county, hungary",
  "wilayah persekutuan putrajaya, malaysia",
  "manyara, tanzania",
  "lubuskie, poland",
  "amman governorate, jordan",
  "tombouctou, mali",
  "region xii, philippines",
  "nakhon pathom, thailand",
  "utena county, lithuania",
  "lang son province, vietnam",
  "a\u00e7ores, portugal",
  "kouilou, republic of the congo",
  "basse-terre, guadeloupe",
  "kyustendil, bulgaria",
  "bistri\u021ba-n\u0103s\u0103ud county, romania",
  "ariana, tunisia",
  "phetchaburi, thailand",
  "portalegre district, portugal",
  "jude\u021bul arge\u0219, romania",
  "gorod sankt-peterburg, russia",
  "kwara, nigeria",
  "damascus governorate, syria",
  "amazonas department, colombia",
  "san cristobal, dominican republic",
  "colonia, uruguay",
  "battambang, cambodia",
  "kelantan, malaysia",
  "tel\u0161iai county, lithuania",
  "dobrich province, bulgaria",
  "mugla, turkey",
  "limon, costa rica",
  "gharb-chrarda-beni hssen, morocco",
  "tizi ouzou, algeria",
  "osmaniye, turkey",
  "st helier, jersey",
  "respublika severnaya osetiya-alaniya, russia",
  "jawa barat, indonesia",
  "tashkent province, uzbekistan",
  "wilayah persekutuan labuan, malaysia",
  "st. croix, u.s. virgin islands",
  "canton of uri, switzerland",
  "i\u0307stanbul province, turkey",
  "san marcos department, guatemala",
  "la guajira, colombia",
  "sakha (yakutiya) republits, russia",
  "tokat, turkey",
  "novo mesto, slovenia",
  "pskovskaya oblast', russia",
  "misiones province, argentina",
  "tigray, ethiopia",
  "egeo, greece",
  "somogy county, hungary",
  "warmi\u0144sko-mazurskie, poland",
  "najran, saudi arabia",
  "limassol, cyprus",
  "lovec, bulgaria",
  "puno, peru",
  "erbil, iraq",
  "al wakrah, qatar",
  "pr, us",
  "vraca, bulgaria",
  "azuay, ecuador",
  "yangon region, myanmar (burma)",
  "ratchaburi, thailand",
  "jeollanam-do, south korea",
  "tumbes, peru",
  "saint catherine parish, jamaica",
  "\u015bl\u0105skie, poland",
  "\u00e7orum, turkey",
  "bruxelles, belgium",
  "al bahah province, saudi arabia",
  "schaan, liechtenstein",
  "kampong cham, cambodia",
  "ruse, bulgaria",
  "\u015f\u0131rnak, turkey",
  "phang-nga, thailand",
  "adjuntas, puerto rico",
  "damietta governorate, egypt",
  "la vega, dominican republic",
  "chimborazo, ecuador",
  "cabo delgado, mozambique",
  "nakhon si thammarat, thailand",
  "municipiul bucure\u0219ti, romania",
  "istria county, croatia",
  "mostaganem, algeria",
  "la romana, dominican republic",
  "central division, fiji",
  "souss-massa-draa, morocco",
  "red sea governorate, egypt",
  "wilayah persekutuan kuala lumpur, malaysia",
  "valverde, dominican republic",
  "razgrad, bulgaria",
  "muramvya, burundi",
  "kisumu, kenya",
  "split-dalmatia county, croatia",
  "saint laurent du maroni, french guiana",
  "manisa, turkey",
  "plateau, nigeria",
  "balochistan, pakistan",
  "utuado, puerto rico",
  "huambo, angola",
  "san germ\u00e1n, puerto rico",
  "yauco, puerto rico",
  "federation of bosnia and herzegovina, bosnia and herzegovina",
  "ica, peru",
  "chang wat nakhon pathom, thailand",
  "tasman, new zealand",
  "laois, ireland",
  "sakhalinskaya oblast', russia",
  "jude\u021bul s\u0103laj, romania",
  "pernik, bulgaria",
  "wallis, switzerland",
  "nord-tr\u00f8ndelag, norway",
  "puerto plata, dominican republic",
  "gouvernorat de tunis, tunisia",
  "new territories, hong kong",
  "tbilisi, georgia",
  "khakasiya republits, russia",
  "akwa ibom, nigeria",
  "capital region, iceland",
  "departamento aut\u00f3nomo de oruro, bolivia",
  "beja district, portugal",
  "trabzon, turkey",
  "los r\u00edos region, chile",
  "east kazakhstan region, kazakhstan",
  "satakunta, finland",
  "tarija department, bolivia",
  "freeport, the bahamas",
  "western division, fiji",
  "atyrau region, kazakhstan",
  "burdur, turkey",
  "nelson, new zealand",
  "southern ostrobothnia, finland",
  "chongqing shi, china",
  "south sinai governorate, egypt",
  "pleven province, bulgaria",
  "enga province, papua new guinea",
  "biskra, algeria",
  "haskovo province, bulgaria",
  "sulawesi selatan, indonesia",
  "chuy province, kyrgyzstan",
  "glarus, switzerland",
  "vega alta, puerto rico",
  "khulna division, bangladesh",
  "umm al quwain, united arab emirates",
  "trujillo, venezuela",
  "agadez, niger",
  "parr\u00f2quia d'andorra la vella, andorra",
  "distrito capital, venezuela",
  "jude\u021bul d\u00e2mbovi\u021ba, romania",
  "kurdistan region, iraq",
  "skopje, macedonia (fyrom)",
  "puntarenas, costa rica",
  "zambezia province, mozambique",
  "goa, india",
  "pasco, peru",
  "kastamonu, turkey",
  "pando department, bolivia",
  "hawally governorate, kuwait",
  "estuaire, gabon",
  "ash sharqia governorate, egypt",
  "copperbelt, zambia",
  "montserrado, liberia",
  "vilniaus apskritis, lithuania",
  "montana province, bulgaria",
  "san pedro de macoris, dominican republic",
  "maritime, togo",
  "upolu, samoa",
  "zamboanga peninsula, philippines",
  "xinjiang weiwuerzizhiqu, china",
  "cymru, united kingdom",
  "dadra and nagar haveli, india",
  "tartu county, estonia",
  "sardinia, italy",
  "maldonado, uruguay",
  "vara\u017edinska \u017eupanija, croatia",
  "mar\u00eda trinidad s\u00e1nchez, dominican republic",
  "g\u00fcm\u00fc\u015fhane, turkey",
  "pomorskie, poland",
  "gu\u00e1rico, venezuela",
  "choc\u00f3, colombia",
  "rabat-sal\u00e9-zemmour-za\u00ebr, morocco",
  "comunitat valenciana, spain",
  "qena governorate, egypt",
  "sacatepequez, guatemala",
  "new providence, the bahamas",
  "magallanes y la ant\u00e1rtica chilena region, chile",
  "brussels hoofdstedelijk gewest, belgium",
  "kunar, afghanistan",
  "oromia, ethiopia",
  "singida, tanzania",
  "caraga, philippines",
  "habaka, jordan",
  "kyustendil province, bulgaria",
  "bonaire, bonaire, sint eustatius and saba",
  "semnan, iran",
  "aksaray, turkey",
  "jawa tengah, indonesia",
  "los lagos region, chile",
  "bio-bio, chile",
  "terengganu, malaysia",
  "v\u00e4sternorrlands l\u00e4n, sweden",
  "saitama-ken, japan",
  "saipan, northern mariana islands",
  "alta verapaz, guatemala",
  "yaracuy, venezuela",
  "aragua, venezuela",
  "\u00e9vora, portugal",
  "lim\u00f3n, costa rica",
  "henan sheng, china",
  "portuguesa, venezuela",
  "mato grosso do sul, paraguay",
  "erzurum, turkey",
  "zhejiang sheng, china",
  "central region, nepal",
  "amazonas, colombia",
  "chang wat chachoengsao, thailand",
  "north karelia, finland",
  "gorod moskva, russia",
  "kef, tunisia",
  "marrakech-tensift-al haouz, morocco",
  "v\u00e2lcea county, romania",
  "\u00f6sterg\u00f6tlands l\u00e4n, sweden",
  "ayd\u0131n province, turkey",
  "oriental, morocco",
  "nidwalden, switzerland",
  "south-east, botswana",
  "faryab, afghanistan",
  "doukkala-abda, morocco",
  "le marin, martinique",
  "san jos\u00e9, uruguay",
  "fort-de-france, martinique",
  "saint george basseterre parish, saint kitts and nevis",
  "gorj county, romania",
  "turkana county, kenya",
  "sliven province, bulgaria",
  "neuqu\u00e9n, argentina",
  "u\u015fak, turkey",
  "takhar, afghanistan",
  "beni, bolivia",
  "ash sharqiyah north governorate, oman",
  "guanacaste, costa rica",
  "kashkadarya province, uzbekistan",
  "hatay province, turkey",
  "roja municipality, latvia",
  "distrito metropolitano de caracas, venezuela",
  "fr, italy",
  "guainia, colombia",
  "baranya, hungary",
  "preah sihanouk, cambodia",
  "gambella, ethiopia",
  "santa fe, argentina",
  "menofia governorate, egypt",
  "mjini magharibi, tanzania",
  "balkh, afghanistan",
  "jambol, bulgaria",
  "primorje-gorski kotar county, croatia",
  "menia governorate, egypt",
  "ingushetiya republits, russia",
  "brunei-muara, brunei",
  "distrito de \u00e9vora, portugal",
  "barinas, venezuela",
  "jude\u021bul neam\u021b, romania",
  "cayenne, french guiana",
  "grande-terre, guadeloupe",
  "central java, republic of indonesia",
  "b\u00e9k\u00e9s county, hungary",
  "imbabura, ecuador",
  "jilin sheng, china",
  "smoljan, bulgaria",
  "lacs, c\u00f4te d'ivoire",
  "calabarzon, colombia",
  "mu\u011fla province, turkey",
  "isparta, turkey",
  "grodno region, belarus",
  "coquimbo region, chile",
  "liaoning sheng, china",
  "jude\u021bul ialomi\u021ba, romania",
  "southern nations, nationalities, and people's region, ethiopia",
  "mopti, mali",
  "lubelskie, poland",
  "alajuela, costa rica",
  "yalova province, turkey",
  "veliko tarnovo province, bulgaria",
  "andijan province, uzbekistan",
  "wales, ",
  "kh\u00e1nh h\u00f2a, vietnam",
  "suez governorate, egypt",
  "puerto rico, us",
  "virgin islands, us",
  "guam, us",
  "palau, us",
];
